apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-creator-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-creator-rolebinding
subjects:
- kind: User
  name: u-ngfkd
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pv-creator-role
  apiGroup: rbac.authorization.k8s.io
