apiVersion: batch/v1
kind: Job
metadata:
  name: hades-winogr-clip-vit-base16-224-2306
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - args:
        - /opt/conda/envs/main/bin/accelerate-launch --mixed_precision=bf16 --gpu_ids=0
          /app/gate/run.py exp_name=hades-winogr-clip-vit-base16-224-2306 model=clip-zero-shot-classification  dataset=winoground
          optimizer.lr=1e-05 trainer=image_to_text_zero_shot_classification evaluator=image_to_text_zero_shot_classification
          seed=2306 train_batch_size=64 eval_batch_size=64
        command:
        - /bin/bash
        - -c
        - --
        env:
        - name: NEPTUNE_API_TOKEN
          value: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiJkOTFjMTY5Zi03ZGUwLTQ4ODYtYWI0Zi1kZDEzNjlkMGI5ZjQifQ==
        - name: NEPTUNE_PROJECT
          value: MachineLearningBrewery/gate-exp-0-8-6
        - name: NEPTUNE_ALLOW_SELF_SIGNED_CERTIFICATE
          value: 'TRUE'
        - name: WANDB_API_KEY
          value: 821661c6ee1657a2717093701ab76574ae1a9be0
        - name: WANDB_ENTITY
          value: machinelearningbrewery
        - name: WANDB_PROJECT
          value: gate-exp-0-8-6
        - name: KAGGLE_USERNAME
          value: antreasantoniou
        - name: KAGGLE_KEY
          value: d14aab63e71334cfa118bd5251bf85da
        - name: PYTEST_DIR
          value: /data/
        - name: EXPERIMENT_NAME
          value: gate-exp-0-8-6
        - name: HF_USERNAME
          value: Antreas
        - name: HF_TOKEN
          value: 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
        - name: HF_CACHE_DIR
          value: /data/
        - name: TOKENIZERS_PARALLELISM
          value: 'false'
        - name: CODE_DIR
          value: /app/
        - name: PROJECT_DIR
          value: /app/
        - name: EXPERIMENT_NAME_PREFIX
          value: gate-exp
        - name: EXPERIMENTS_DIR
          value: /data/experiments/
        - name: EXPERIMENT_DIR
          value: /data/experiments/
        - name: DATASET_DIR
          value: /data/
        - name: MODEL_DIR
          value: /data/model/
        image: ghcr.io/antreasantoniou/gate:latest
        imagePullPolicy: Always
        name: hades-winogr-clip-vit-base16-224-2306
        resources:
          limits:
            nvidia.com/gpu: 1
          requests: {}
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /data/
          name: gate-disk
      restartPolicy: Never
      volumes:
      - emptyDir:
          medium: Memory
          sizeLimit: 100G
        name: dshm
      - name: gate-disk
        persistentVolumeClaim:
          claimName: gate-pvc-40
