name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main  # Replace with your default branch name, e.g., 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        bash install install.sh
        pip3 install .
    - name: Build Sphinx documentation # use "sphinx-apidoc -o docs/source gate" when new modules are added prior to pushing
      run: |
        cd docs  # Replace 'docs' with the path to your Sphinx documentation directory 
        make html

    - name: Deploy to docs branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        publish_dir: ./docs/_build/html
        publish_branch: docs-pages
        user_name: 'GitHub Actions'
        user_email: 'actions@github.com'
        force_orphan: true
